version: '3'
services:
    postgresdb:
        image: postgres:14.1
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
        ports:
          - '5438:5432'
        volumes:
          - ../data/volume:/var/lib/postgresql/data
