version: '3'
services:
    db:
        image: postgres:14.1
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
        ports:
          - '5432:5432'
        volumes:
          - ./volume:/var/lib/postgresql/data
          - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
